#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  user: lookup('env', 'USER')
  connection: local
  gather_facts: no

  vars_files:
    - vars/main.yml

  tasks:
    - name: Homebrew tap
      homebrew_tap: name={{ item.name }} state={{ item.state }}
      with_items: "{{ homebrew_taps }}"
      tags:
        - taps

    - name: Homebrew installs
      homebrew: name={{ item.name }} state={{ item.state }} install_options={{ item.install_options | default("")  }}
      with_items: "{{ homebrew_packages }}"
      tags:
        - installs

    - name: Homebrew cask installs
      homebrew_cask: name={{ item.name }} state={{ item.state }}
      with_items: "{{ homebrew_casks }}"
      tags:
        - casks

    - name: Install Ruby gems
      gem: name={{ item.name }} version={{ item.version }} state={{ item.state }}
      with_items: "{{ homebrew_ruby_gems }}"
      tags:
        - gems

    - name: Python packages
      pip:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items: "{{ homebrew_python_packages }}"
      tags:
        - python-pkgs

    - name: Is Atom editor customizations already installed?
      stat:
        path: $HOME/.atom/packages/language-babel/
      register: language_babel
      changed_when: False
      tags:
        - never
        - atom-extra

    - name: Atom editor customizations; for React syntax highlighting
      command: apm install language-babel
      when: language_babel.stat.exists == False
      tags:
        - never
        - atom-extra
 
